version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000" #local:container

  # app:
  #   image: web
  #   resources:
  #     limits:
  #       cpus: '0.50'
  #       memory: 1024M
  #     reservations:
  #       cpus: '0.50'
  #       memory: 1024M